name: Compile and Publish Binaries

on: 
  push:
    branches:
        - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Clear PKG_CONFIG_PATH
        shell: bash
        run: echo "PKG_CONFIG_PATH=" >> $GITHUB_ENV
    
      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          audit_token: ${{ secrets.MY_CONAN_AUDIT_TOKEN }}
          cache_packages: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xorg-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libwayland-dev \
            wayland-protocols \
            libxkbcommon-dev \
            libudev-dev \
            libx11-xcb-dev \
            libxcb-util-dev \
            libxcb-glx0-dev \
            libxcb-render0-dev \
            libxcb-render-util0-dev \
            libxcb-xkb-dev \
            libxcb-icccm4-dev \
            libxcb-image0-dev \
            libxcb-keysyms1-dev \
            libxcb-randr0-dev \
            libxcb-shape0-dev \
            libxcb-sync-dev \
            libxcb-xfixes0-dev \
            libxcb-xinerama0-dev \
            libxcb-dri3-dev \
            libxcb-cursor-dev \
            libxcb-dri2-0-dev \
            libxcb-present-dev \
            libxcb-composite0-dev \
            libxcb-ewmh-dev \
            libxcb-res0-dev
        
      - name: Install Conan dependencies with lockfile
        run: conan install . --lockfile=conan.lock --lockfile-partial --lockfile-out=conan.lock --build=missing

      - name: Configure build (Windows)
        if: runner.os == 'Windows'
        run: cmake --preset conan-default

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build --preset conan-release

      - name: Configure build (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake --preset conan-release

      - name: Build (Linux/macOS)
        if: runner.os != 'Windows'
        run: cmake --build --preset conan-release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/*
          asset_name: birdgame_${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
